# Generated by Django 5.1.3 on 2024-11-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='slug',
            field=models.SlugField(default='default'),
            preserve_default=False,
        ),
    ]
