# Generated by Django 5.1.3 on 2024-11-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_client_coach_alter_recommendation_title'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workout_plan',
            name='api_workout_client__493dd9_idx',
        ),
        migrations.AddIndex(
            model_name='workout_plan',
            index=models.Index(fields=['client'], name='api_workout_client__ece35d_idx'),
        ),
    ]
