# Generated by Django 5.1.3 on 2024-11-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_workout_plan_api_workout_client__493dd9_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workout_plan',
            name='api_workout_client__ece35d_idx',
        ),
        migrations.AddIndex(
            model_name='workout_plan',
            index=models.Index(fields=['client', 'coach'], name='api_workout_client__493dd9_idx'),
        ),
        migrations.AddConstraint(
            model_name='workout_plan',
            constraint=models.UniqueConstraint(fields=('type',), name='unique_type'),
        ),
    ]
