# Generated by Django 5.1.3 on 2024-11-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_meal_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
