# Generated by Django 5.1.3 on 2024-11-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_workout_plan_api_workout_client__ece35d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='meal',
            name='unique_meal_user',
        ),
        migrations.RemoveConstraint(
            model_name='workout_plan',
            name='unique_type',
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(fields=('type', 'workout_plan', 'client'), name='unique_meal_user'),
        ),
        migrations.AddConstraint(
            model_name='workout_plan',
            constraint=models.UniqueConstraint(fields=('type', 'client'), name='unique_type'),
        ),
    ]
