# Generated by Django 5.1.3 on 2024-11-26 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_workoutplan_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='workout_plans',
        ),
        migrations.AddField(
            model_name='meal',
            name='workout_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workout_plan', to='api.workoutplan'),
        ),
    ]
