# Generated by Django 5.1.3 on 2024-11-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_meal_unique_meal_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='meal',
            name='unique_meal_user',
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(fields=('type', 'client', 'coach'), name='unique_meal_user'),
        ),
    ]
