# Generated by Django 5.1.3 on 2024-12-02 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_age_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='height',
            field=models.PositiveIntegerField(default=150, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='weight',
            field=models.PositiveIntegerField(default=150, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'client'), ('coach', 'coach')], max_length=10),
        ),
    ]
