# Generated by Django 5.1.3 on 2024-12-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_client_height_client_weight_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='goal',
            field=models.CharField(choices=[('Lose Weight', 'Lose Weight'), ('Build Muscles', 'Build Muscles'), ('Special Program', 'Special Program')], max_length=20),
        ),
    ]
