# Generated by Django 5.1.3 on 2024-12-01 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_meal_unique_meal_user_meal_unique_meal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout_plan',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='api.client'),
        ),
    ]
