# Generated by Django 5.1.3 on 2024-11-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_meal_workout_plans_meal_workout_plan'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['meal_type', 'workout_plan'], name='api_meal_meal_ty_759b47_idx'),
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(fields=('meal_type', 'workout_plan'), name='unique_meal_user'),
        ),
    ]
