# Generated by Django 5.1.3 on 2024-11-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_meal_api_meal_meal_ty_759b47_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['eating_time']},
        ),
    ]
