# Generated by Django 5.1.3 on 2024-11-26 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_meal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='workout_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meals', to='api.workoutplan'),
        ),
    ]
