# Generated by Django 5.1.3 on 2024-12-09 10:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_options_user_api_user_usernam_edfd3a_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='api.coach'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='coach',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('client', 'client'), ('coach', 'coach')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='workout_plan',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coach'),
        ),
    ]
