# Generated by Django 5.1.3 on 2024-11-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_meal_workout_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutplan',
            old_name='coaches',
            new_name='coach',
        ),
        migrations.AlterField(
            model_name='meal',
            name='slug',
            field=models.SlugField(blank=True, default='user1c'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='slug',
            field=models.SlugField(blank=True, default='user1c'),
            preserve_default=False,
        ),
    ]
