# Generated by Django 5.1.3 on 2024-12-09 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_client_coach_alter_coach_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='age',
            field=models.PositiveIntegerField(default='15', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coach',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'client'), ('coach', 'coach')], default='coach', max_length=10),
            preserve_default=False,
        ),
    ]
