# Generated by Django 5.1.3 on 2024-11-27 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_coaches_workoutplan_coach_alter_meal_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='coaches',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='client',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_client', to='api.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='coach',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_coach', to='api.coach'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='client',
            field=models.OneToOneField(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='workoutplan', to='api.client'),
        ),
    ]
