# Generated by Django 5.1.3 on 2024-11-28 06:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_recommendation_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
